#!/usr/bin/env python3
"""Instinct mod icon — emits icon.glyph (32px native).

A glowing heart-rose paw print pressed into a weathered dark stone slab
(DESIGN.md §1). Render the glyph with --scale-to 128 / 512 for the masters.
Deterministic: geometry and shading are computed, no randomness.
"""

import os

SIZE = 32

INK = "#0a0a0a"
RING = "#050505"          # carved ring around the paw
RIM = "#3a3a3a"           # slab top rim light
STONE = ["#2c2c2c", "#252525", "#1f1f1f", "#181818"]  # vertical ramp
CRACK = "#111111"
BRIGHT = "#f5a8c8"        # rose glow core
AMBER = "#e5709b"         # heart rose
SHADE = "#c25580"
DEEP = "#98405f"
GLOW = "#e5709b55"        # soft halo on the stone

# paw geometry: four toe ellipses + one pad ellipse (cx, cy, rx, ry)
TOES = [
    (8.5, 11.0, 2.2, 3.0),   # outer left
    (13.0, 7.5, 2.1, 3.2),   # inner left
    (19.0, 7.5, 2.1, 3.2),   # inner right
    (23.5, 11.0, 2.2, 3.0),  # outer right
]
PAD = (16.0, 20.0, 7.4, 5.4)

CRACKS = [(4, 25), (5, 26), (6, 26), (25, 5), (26, 5), (27, 24), (28, 24), (3, 9), (28, 13)]


def in_ellipse(x, y, e, grow=0.0):
    cx, cy, rx, ry = e
    return ((x - cx) / (rx + grow)) ** 2 + ((y - cy) / (ry + grow)) ** 2 <= 1.0


def paw(x, y, grow=0.0):
    return any(in_ellipse(x, y, e, grow) for e in TOES + [PAD])


def in_slab(x, y):
    r = 3  # corner radius
    if not (1 <= x <= 30 and 1 <= y <= 30):
        return False
    for cx, cy in ((1 + r, 1 + r), (30 - r, 1 + r), (1 + r, 30 - r), (30 - r, 30 - r)):
        if (x < 1 + r or x > 30 - r) and (y < 1 + r or y > 30 - r):
            if (x - cx) ** 2 + (y - cy) ** 2 > (r + 0.5) ** 2:
                return False
    return True


def slab_edge(x, y):
    return in_slab(x, y) and not all(
        in_slab(x + dx, y + dy) for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1))
    )


def paw_color(x, y):
    # light from the upper left: bright core toward (13, 17), shading outward
    for e in TOES:
        if in_ellipse(x, y, e):
            if in_ellipse(x, y, e, -0.9):
                return BRIGHT if (x <= e[0] and y <= e[1]) else AMBER
            return SHADE if (x > e[0] or y > e[1]) else AMBER
    if in_ellipse(x, y, PAD, -3.2):
        return BRIGHT
    if in_ellipse(x, y, PAD, -1.4):
        return AMBER if (x <= PAD[0] + 2 and y <= PAD[1] + 2) else SHADE
    return DEEP if (x > PAD[0] and y > PAD[1]) else SHADE


def stone_color(x, y):
    if (x, y) in CRACKS:
        return CRACK
    if y <= 2:
        return RIM
    return STONE[min((y - 1) * len(STONE) // 30, len(STONE) - 1)]


def cell(x, y):
    if not in_slab(x, y):
        return None
    if slab_edge(x, y):
        return INK
    if paw(x, y):
        return paw_color(x, y)
    if paw(x, y, 0.9):
        return RING
    if paw(x, y, 1.9):
        return GLOW
    return stone_color(x, y)


def main():
    grid = [[cell(x, y) for x in range(SIZE)] for y in range(SIZE)]
    colors = []
    for row in grid:
        for c in row:
            if c and c not in colors:
                colors.append(c)
    chars = "@abcdefghijkmnopqrstuvwxyz0123456789"
    assert len(colors) <= len(chars)
    char_of = {c: chars[i] for i, c in enumerate(colors)}

    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "icon.glyph")
    with open(out, "w") as f:
        f.write("# Instinct mod icon — generated by icon.gen.py (edit the generator, re-run).\n")
        f.write("# Glowing heart-rose paw print carved into a weathered dark stone slab.\n")
        f.write("# Masters: --scale-to 128 -> art/icon-128.png, --scale-to 512 -> art/icon-512.png\n")
        f.write(f"size: {SIZE}\n")
        f.write("kind: icon\n")
        f.write("ships: art/icon-128.png 128\n")
        f.write("ships: art/icon-512.png 512\n")
        f.write("ships: src/main/resources/assets/instinct/icon.png 128\n")
        f.write("ships: site/assets/icon.png 128\n")
        f.write("\nlegend:\n")
        for c in colors:
            f.write(f"  {char_of[c]} {c}\n")
        f.write("  . transparent\n\nframe:\n")
        for row in grid:
            f.write("  " + "".join(char_of[c] if c else "." for c in row) + "\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
