#!/usr/bin/env python3
"""Generator for the Instinct keepsake collar item sprite (16x16).

A leather collar ring — a russet/tan leather band curved into a loop with a
1px ink silhouette outline on both the outer and inner edges — with a small
pewter name-tag hanging from the bottom. Light from the top-left: tan highlight
upper-left, russet core, deep-leather shadow lower-right. Emits the .glyph spec
that glyph.py rasterizes; edit this generator, never the emitted grid.
"""
from pathlib import Path

N = 16
CX, CY = 7.5, 7.2       # ring centre
R_OUT = 6.7             # outer radius
R_IN = 3.3              # hole radius
TAG_CX, TAG_CY = 7.5, 13.4
TAG_R = 2.0

# Legend chars
INK, TAN, RUSSET, DEEP, BONE, ASH, EMPTY = "@", "t", "r", "d", "h", "s", "."


def dist(x, y, cx, cy):
    return ((x - cx) ** 2 + (y - cy) ** 2) ** 0.5


def in_ring(x, y):
    d = dist(x, y, CX, CY)
    return R_IN <= d <= R_OUT


def in_tag(x, y):
    return dist(x, y, TAG_CX, TAG_CY) <= TAG_R


def cell(x, y):
    # Tag (metal) takes priority where it overlaps the ring's lower edge.
    if in_tag(x, y):
        # Ink outline on the tag's rim.
        for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            if not in_tag(x + dx, y + dy) and not in_ring(x + dx, y + dy):
                return INK
        # Pewter ramp: bright upper-left, ash lower-right.
        return BONE if (x - TAG_CX) + (y - TAG_CY) < 0 else ASH
    if in_ring(x, y):
        # Ink outline where the band meets the hole or open air.
        for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            if not in_ring(x + dx, y + dy) and not in_tag(x + dx, y + dy):
                return INK
        # Leather ramp along the top-left light direction.
        light = (x - CX) + (y - CY)   # negative = upper-left (lit)
        if light < -3.0:
            return TAN
        if light > 3.5:
            return DEEP
        return RUSSET
    return EMPTY


def main():
    rows = ["".join(cell(x, y) for x in range(N)) for y in range(N)]
    spec = []
    spec.append("# Instinct 16x16 keepsake collar — a leather collar loop with a pewter name-tag.")
    spec.append("# Russet/tan leather ramp (tan highlight upper-left, deep-leather shadow lower-right),")
    spec.append("# ink silhouette on the outer and inner edges, a small bone/ash metal tag hanging below.")
    spec.append("# GENERATED by keepsake-collar-16.gen.py — edit the generator, not this grid.")
    spec.append("size: 16")
    spec.append("kind: sprite")
    spec.append("ships: src/main/resources/assets/instinct/textures/item/keepsake_collar.png")
    spec.append("edge: shaped")
    spec.append("")
    spec.append("legend:")
    spec.append("  @ ink")
    spec.append("  t instinct.tan")
    spec.append("  r instinct.russet")
    spec.append("  d smoke")
    spec.append("  h bone")
    spec.append("  s ash")
    spec.append("  . transparent")
    spec.append("")
    spec.append("frame:")
    for row in rows:
        spec.append("  " + row)
    spec.append("")
    out = Path(__file__).with_name("keepsake-collar-16.glyph")
    out.write_text("\n".join(spec))
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
